language: cpp

compiler: gcc

addons:
    apt:
        packages:
        - libboost-filesystem-dev
        - libboost-date-time-dev
        - libboost-locale-dev
        - libfreeimage-dev
        - libfreetype6-dev
        - libeigen3-dev
        - libcurl4-openssl-dev
        - libasound2-dev
        - libgl1-mesa-dev
        - build-essential
        sources:
        - libsdl2-dev
        - libboost-system-dev

before_script: cmake
script: make
